name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v1

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.3'
        bundler-cache: true

    - name: Rspec - Build and run tests
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec spec
